config/routes.rb
Onefourteenbailey::Application.routes.draw do
  root to: 'static_pages#home'
  match '/services', to: 'static_pages#services'
  match '/about', to: 'static_pages#about'
  match '/different', to: 'static_pages#different'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :body, :updates

  validates :name, :email, :phone, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Thank you! Your message was successfully sent. We will be in touch soon.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "One Fourteen Bailey Interior Design"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
	def description(page_description)
		base_description = "A new approach to interior design. Spaces that inspire - ideas that design happiness."
		if page_description.empty?
			base_description
		else
			"#{page_description}"
		end		
	end	
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contact/new.html.erb
<% provide(:title, "Contact Us") %>
<%= form_for @message, :url => contact_path do |form| %>
  <div id="contact_left_margin">
     <fieldset id="contact_width">
        <legend class="lightgray_text">Say hi.</legend>
        <p class="help-block gray_text" id="contact_form_text">We would love to work with you. To schedule a free design consultation, simply contact us by filling in the form below, or calling <strong>413-358-5566.</strong>
        </p>
        <br>
        <%= form.text_field :name, :class => "span3", :required => true, :placeholder => "Name"  %>
        <br>
        <%= form.text_field :email, :class => "span3", :required => true, :placeholder => "Email"  %>
        <br>
        <%= form.telephone_field :phone, :class => "span3", :required => true, :placeholder => "Phone"  %>
        <br>
        <%= form.text_area :body, :class => "span3", :rows => 5, :required => true, :placeholder => "Tell us a little bit about your project..."  %>
        <br>
        <label class="checkbox gray_text" id="checkbox_font">
          <%= form.check_box :updates %> Yes, I would like to receive One Fourteen Bailey email updates
        </label><br> 
    
    </fieldset>
    
    <fieldset class="actions">
      <%= form.submit "Submit", :class=> "btn" %>
    </fieldset>
  </div>  
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="footer-left">
		<small> P: 413-358-5566</small>
	</div>	
	<div class="pull-right footer-right">
		<small> © ONE FOURTEEN BAILEY, LLC. </small>
	</div>
</footer>	

app/views/layouts/_header.html.erb
<div class="center top-logo">
	<%= link_to(image_tag("logo.png", :alt => "One Fourteen Bailey Logo"),root_path) %>
</div>
<div class="navbar">
  	<div class="navbar-inner pull-center">
  		<div class="container">
	      	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	      	</a>
		    <div class="nav-collapse collapse pull-center" id="nav_contact_margin">
			    <ul class="nav">
			      <li class="<%= 'active' if current_page?(root_path) %>" id="work">
			      	<%= link_to "the gallery", root_path %>
			      </li>
			      <li class="<%= 'active' if current_page?(services_path) %>" id="services">
			      	<%= link_to "design services", services_path %>
			      </li>
			      <li class="<%= 'active' if current_page?(different_path) %>">
			      	<%= link_to "how we are different", different_path %>
			      </li>
			      <li class="<%= 'active' if current_page?(about_path) %>">
			      	<%= link_to "about us", about_path %>
			      </li>
			      <li class="<%= 'active' if current_page?(contact_path) %>" id="nav_contact_margin">
			      	<%= link_to "contact us", contact_path %>
			      </li>
			    </ul>
			</div>
		</div>
  	</div>
</div>
<script>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="<%= description(yield(:description)) %>" />
  <meta name="keywords" content="Interior Design, Jodi Dias, One Fourteen Bailey" />
  <%= stylesheet_link_tag   "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
	<% flash.each do |key,value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
	<% end %>	
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37321940-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/static_pages/about.html.erb
<% provide(:title, "Get To Know Us") %>
<div class="image_center about_center">
	<div>
		<%= image_tag("about_jodi.png", :alt => "Jodi Dias", :class => "img-circle", :id => "jodi_image_left") %>
		<div id="jodi_text_width">
			<p class="small_font" id="jodi_copy_right"><strong> Jodi </strong> 
				<br>
				<br>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis ipsum enim. Sed porta euismod sapien sit amet gravida. Donec congue nulla non risus pulvinar non imperdiet risus tincidunt. </p>
		</div>
	</div>
	<br>

	<div>
		<div id="delana_text_width">
			<p class="small_font" id="delana_copy_left">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis ipsum enim. Sed porta euismod sapien sit amet gravida. Donec congue nulla non risus pulvinar non imperdiet risus tincidunt.</p>
		</div>
		
		<%= image_tag("about_delana.png", :alt => "Delana Joldersma", :class => "img-circle", :id => "delana_image_right") %>
	</div>
	<br>

	<div>
		<%= image_tag("about_judy.png", :alt => "Judy Dias", :class => "img-circle", :id => "judy_image_left") %>

		<div id="judy_text_width">
			<p class="small_font" id="judy_copy_right">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut quis ipsum enim. Sed porta euismod sapien sit amet gravida. Donec congue nulla non risus pulvinar non imperdiet risus tincidunt.</p>
		</div>
	</div>
</div>

app/views/static_pages/different.html.erb
<% provide(:title, "How We Are Different") %>
<div class="image_center content_center">
	<div class="center" id="differences_left">
		<%= image_tag("how-we-are-different_1.png", :alt => "One Fourteen Bailey Services") %>
	</div>

	<div class="center" id="differences_right">
		
		<h4 class="gray_text left text_width image_center">A new approach to designing the perfect space</h4>
		<br>
		<p class="small_font gray_text left text_width image_center">
			Our <strong>fresh ideas and innovative designs</strong> offer the opportunity to create a home that is completely unique to you.
		<br>
		<br>
			With our <strong>affordable design plan</strong>, interior design doesn’t need to be expensive because you will have complete control over your money and how your budget is spent.
		<br>
		<br>
			Our <strong>energetic and collaborative process</strong> will help you learn how to plan and create, leaving you with a place that is all your own.
		</p>
		<br>
		<%= link_to "SCHEDULE A FREE DESIGN CONSULTATION TODAY", contact_path, :class => "image_center btn btn-primary custom" %>
	</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Our Work") %>
<div id="myCarousel" class="carousel slide">
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item">
    	<div class="center">
    		<%= image_tag("home_slide_1.png", :alt => "One Fourteen Bailey Slide Image #1") %>
    	</div>
    </div>	
    <div class="item">
    	<div class="center">
    		<%= image_tag("home_slide_2.png", :alt => "One Fourteen Bailey Slide Image #2") %>
    	</div>
    </div>	
    <div class="item">
    	<div class="center">
    		<%= image_tag("home_slide_3.png", :alt => "One Fourteen Bailey Slide Image #3") %>
    	</div>
    </div>	
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

app/views/static_pages/services.html.erb
<% provide(:title, "Services We Offer") %>
<div class="image_center content_center">
	
	<div class="center" id="services_left">
		<h4 class="gray_text left text_width image_center">Spaces that inspire — ideas that design happiness</h4>
		<br>
		<p class="small_font gray_text left text_width image_center">
			Perfect for the do-it-yourself enthusiast looking for a creative kick-start, One Fourteen Bailey interior design offers inspiration, creative direction, and full design project plans, all for one low price.  
			<br>
			<br>
			This new approach to the interior design process allows for flexibility and control of your project, while providing the highest quality interior design service.
		</p>
		<br>
		<%= link_to "SCHEDULE A FREE DESIGN CONSULTATION TODAY", contact_path, :class => "image_center btn btn-primary custom" %>
	</div>
	
	<div class="center" id="services_right">
		<%= image_tag("services_1.png", :alt => "One Fourteen Bailey Services") %>
	</div>	
</div>